version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: user
  MYSQL_PASSWORD: test
  MYSQL_DATABASE: fb_distribue
  MYSQL_PORT: "${PORT_SQL}"


services:
  db:
    image: mysql:5.7
    ports:
      - "${PORT_SQL}:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: test
      MYSQL_HOST: localhost
    restart: unless-stopped
    volumes:
      - ./db/fb_distribue.sql:/docker-entrypoint-initdb.d/sql.sql
  www:
    container_name: ${CONTAINER_NAME}
    build: .
    depends_on:
      - db
    ports:
      - "${PORT_SERVER}:80"
    volumes:
      - ./src:/var/www/html/fb-distribue/src
    links:
      - db
    environment: 
      <<: *common-variables
      MYSQL_HOST_IP: db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - ${PORT_PMA}:80
    depends_on:
      - db
    restart: always
  
volumes:
  persistent:

networks:
  default:
    external:
      name: sr05-red
    
